=== codewithkristian/mailinglisthackers-members/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://www.mailinglisthackers.com/member.schema.json",
  "title": "Members",
  "description": "Mailing List Hackers members",
  "type": "object",
  "properties": {
    "name": {
      "description": "Member name",
      "type": "string"
    },
    "description": {
      "description": "Description",
      "type": "string"
    },
    "url": {
      "description": "Newsletter URL",
      "type": "string"
    },
    "newsletter": {
      "description": "Newsletter name",
      "type": "string"
    },
    "newsletter_url": {
      "description": "Newsletter URL",
      "type": "string"
    },
    "image": {
      "description": "Image URL",
      "type": "string"
    },
    "twitter": {
      "description": "Twitter URL",
      "type": "string"
    }
  },
  "required": [
    "name",
    "newsletter",
    "description",
    "image",
    "newsletter_url"
  ]
}

=== codewithkristian/mailinglisthackers-members/members/billflitter.json
{
  "name": "Bill Flitter",
  "twitter": "https://twitter.com/fixmygrowth",
  "url": "https://FixMyGrowth.com",
  "description": "20 years of experience helping startups grow.",
  "newsletter": "Fix My Growth",
  "newsletter_url": "https://FixMyGrowth.com",
  "image": "https://fixmygrowth.com/wp-content/uploads/2020/09/Bill-Flitter-Image-Round-2.png"
}

=== codewithkristian/mailinglisthackers-members/members/frank.json
{
  "name": "Frank Meeuwsen",
  "twitter": "https://twitter.com/frankmeeuwsen",
  "url": "https://thanksforsubscribing.app",
  "description": "Give your inbox more love with some of the best and interesting newsletter on this planet. With Thanks for Subscribing I collect, curate and share those nuggets with other newsletter creators, fans and afficionados.",
  "newsletter": "Thanks for Subscribing",
  "newsletter_url": "https://thanksforsubscribing.app",
  "image": "https://secure.gravatar.com/avatar/ae0d61ecec9ba68060523144917aed32"
}

=== codewithkristian/mailinglisthackers-members/members/josephech.json
{
  "name": "Joseph Echavarria",
  "twitter": "https://twitter.com/josephech",
  "url": "www.josephech.com",
  "description": "Joseph.Ech. is an Architectural Designer,  Content Creator, and a huge Coffee Addict ☕️",
  "newsletter": "Life of a Designer",
  "newsletter_url": "https://josephech.substack.com/",
  "image": "https://i.postimg.cc/G3YBrBjh/Joseph.jpg"
}

=== codewithkristian/mailinglisthackers-members/members/piotrgaczkowski.json
{
  "name": "Piotr Gaczkowski",
  "twitter": "https://twitter.com/doomhammerng",
  "url": "https://doomhammer.info",
  "description": "Creator. Efficiency Hacker. Human Jukebox. I want to inspire creative people to search for their own path.",
  "newsletter": "Bit Better Club",
  "newsletter_url": "https://bitbetter.club",
  "image": "https://doomhammer.info/img/photo.jpg"
}

=== codewithkristian/mailinglisthackers-members/members/erickson.json
{
  "name": "Ryan Erickson",
  "twitter": "https://twitter.com/ryanerickson",
  "url": "https://pmfive.co",
  "description": "I write about Project Management covering leadership, business acument, training, and industry updates.",
  "newsletter": "The Stakeholder Report",
  "newsletter_url": "https://thestakeholderreport.substack.com",
  "image": "https://res.cloudinary.com/ryanerickson/image/upload/v1595707856/pmfive/FullSizeRender_Original_o.jpg"
}
